import { useMemo, useRef, useState } from 'react'
import Sidebar from './components/Sidebar'
import MobileDocumentStrip from './components/MobileDocumentStrip'
import AnswerCard from './components/AnswerCard'
import EmptyState from './components/EmptyState'
import InputBar from './components/InputBar'
import SourcesPanel from './components/SourcesPanel'
import NotesPanel from './components/NotesPanel'
import { queryBackend, uploadFile, isBackendConfigured } from './api'

// Documents come from actual uploads (see handleFilesAdded) — start empty
// so the sidebar reflects only what's really been uploaded this session.
const INITIAL_DOCS = []

const NAV_TABS = ['Focus', 'Resources', 'Notes']

// STATUS_LABEL / description text shown on each Resources-tab card, keyed
// off the real upload lifecycle in `documents` (see handleFilesAdded).
const STATUS_LABEL = {
  ready: 'READY',
  processing: 'PROCESSING…',
  error: 'UPLOAD FAILED',
}

const STATUS_DESCRIPTION = {
  ready: 'Indexed and available to the assistant.',
  processing: 'Still being read and indexed — hang tight.',
  error: 'Something went wrong ingesting this file. Try re-uploading.',
}

/**
 * Top-level app shell wiring together the full flow: ask -> thinking ->
 * answer/empty, plus the Resources tab (multi-document source selection)
 * and the mobile horizontal bookshelf.
 */
export default function App() {
  const [activeTab, setActiveTab] = useState('Focus')
  const [activeDocId, setActiveDocId] = useState(null)
  const [webSearchEnabled, setWebSearchEnabled] = useState(false)
  const [thinking, setThinking] = useState(false)
  // null until the first real answer arrives; App starts on the empty state.
  const [exchange, setExchange] = useState(null)
  const [showEmpty, setShowEmpty] = useState(true)
  // Which quiet-state copy EmptyState shows: 'no-answer' (checked sources,
  // nothing confirmed an answer) or 'error' (backend unreachable/misconfigured/
  // the request itself failed). See handleAsk.
  const [emptyVariant, setEmptyVariant] = useState('no-answer')
  const [documents, setDocuments] = useState(INITIAL_DOCS)
  // Stable per-session id, required by the backend to key conversation
  // memory (backend/rag.py: SESSIONS dict, keyed by this). Generated once on
  // mount and regenerated by "New Research" so that starts a fresh backend
  // conversation too, not just a fresh-looking UI.
  const [sessionId, setSessionId] = useState(() => crypto.randomUUID())
  // Hidden <input type="file"> triggered by the Resources tab's "Add
  // Resource" button — reuses the exact same handleFilesAdded pipeline
  // (and therefore the same real /upload call) as the Sidebar's UploadZone,
  // just without duplicating its full drag-and-drop UI in a button context.
  const resourceInputRef = useRef(null)

  // Resources-tab cards, derived from the same `documents` state the
  // Sidebar renders, so this tab reflects what's actually been uploaded.
  const sources = useMemo(
    () =>
      documents.map((doc) => ({
        id: doc.id,
        type: doc.type,
        title: doc.name,
        description: STATUS_DESCRIPTION[doc.status] ?? '',
        relevance: STATUS_LABEL[doc.status] ?? doc.status?.toUpperCase() ?? '',
        sourceLabel: `${doc.type === 'pdf' ? 'PDF' : 'IMAGE'} SOURCE`,
      })),
    [documents]
  )

  // Called by UploadZone (via Sidebar) whenever the user drops/picks files.
  // If VITE_API_URL isn't set, uses the fake processing->ready timeout
  // (expected/normal — no backend to call yet). If it IS set, tries the
  // real /upload endpoint and shows a genuine 'error' status on failure
  // instead of masking it — a real, configured backend failing is a bug
  // worth seeing during integration testing, not something to fake past.
  function handleFilesAdded(files) {
    const newDocs = files.map((file) => ({
      id: crypto.randomUUID(),
      file,
      name: file.name,
      type: file.type === 'application/pdf' ? 'pdf' : 'image',
      status: 'processing',
    }))
    setDocuments((prev) => [...prev, ...newDocs])

    newDocs.forEach(async (doc) => {
      if (isBackendConfigured()) {
        try {
          const result = await uploadFile(doc.file)
          setDocuments((prev) =>
            prev.map((d) => (d.id === doc.id ? { ...d, status: 'ready', file_id: result.file_id } : d))
          )
        } catch (err) {
          console.warn(`[studymate] upload of "${doc.name}" failed:`, err.message)
          setDocuments((prev) =>
            prev.map((d) => (d.id === doc.id ? { ...d, status: 'error' } : d))
          )
        }
        return
      }

      // No backend configured at all — this is the expected pre-integration
      // state, so fake the ready transition rather than showing an error.
      setTimeout(() => {
        setDocuments((prev) =>
          prev.map((d) => (d.id === doc.id ? { ...d, status: 'ready' } : d))
        )
      }, 1200 + Math.random() * 800)
    })
  }

  async function handleAsk(question) {
    setActiveTab('Focus')
    setShowEmpty(false)
    setThinking(true)

    if (!isBackendConfigured()) {
      // No backend configured at all — this is a real misconfiguration,
      // not something to paper over with a fake answer.
      setThinking(false)
      setEmptyVariant('error')
      setShowEmpty(true)
      return
    }

    try {
      const readyFileIds = documents
        .filter((d) => d.status === 'ready' && d.file_id)
        .map((d) => d.file_id)
      const result = await queryBackend(question, webSearchEnabled, sessionId, readyFileIds)
      setThinking(false)
      if (!result) {
        // Backend explicitly signaled insufficient sources — genuine
        // zero-hallucination case, not a failure.
        setEmptyVariant('no-answer')
        setShowEmpty(true)
      } else {
        setExchange({ ...result, question })
      }
    } catch (err) {
      // Real failure: network error, timeout, non-2xx, or malformed shape.
      // Show it as an error rather than fabricating an answer.
      console.warn('[studymate] backend query failed:', err.message)
      setThinking(false)
      setEmptyVariant('error')
      setShowEmpty(true)
    }
  }

  return (
    <div className="flex h-screen w-full relative overflow-hidden">
      <Sidebar
        documents={documents}
        activeDocId={activeDocId}
        onSelectDocument={setActiveDocId}
        onFilesAdded={handleFilesAdded}
        onNewResearch={() => {
          setShowEmpty(true)
          setEmptyVariant('no-answer')
          setActiveTab('Focus')
          setExchange(null)
          setSessionId(crypto.randomUUID())
        }}
      />

      <main className="flex-1 flex flex-col relative overflow-hidden">
        <header className="h-16 w-full max-w-[1100px] mx-auto flex items-center justify-between px-page-margin shrink-0">
          <div className="flex items-center gap-8">
            {NAV_TABS.map((tab) => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={`font-label-mono text-label-mono pb-1 transition-colors ${
                  activeTab === tab
                    ? 'text-primary border-b-2 border-primary'
                    : 'text-on-surface-variant hover:text-primary'
                }`}
              >
                {tab}
              </button>
            ))}
          </div>
        </header>

        <MobileDocumentStrip
          documents={documents}
          activeDocId={activeDocId}
          onSelectDocument={setActiveDocId}
          onFilesAdded={handleFilesAdded}
        />

        <div className="flex-1 overflow-y-auto pb-64 md:pb-48">
          {activeTab === 'Resources' ? (
            <>
              <input
                ref={resourceInputRef}
                type="file"
                accept=".pdf,.jpg,.jpeg,.png,.webp"
                multiple
                className="hidden"
                onChange={(e) => {
                  if (e.target.files?.length) handleFilesAdded(Array.from(e.target.files))
                  e.target.value = '' // allow re-selecting the same file later
                }}
              />
              <SourcesPanel
                sources={sources}
                activeSourceId={activeDocId}
                onSelectSource={setActiveDocId}
                onAddResource={() => resourceInputRef.current?.click()}
              />
            </>
          ) : activeTab === 'Notes' ? (
            <NotesPanel />
          ) : (
            <div className="max-w-[800px] mx-auto px-page-margin pt-8 relative">
              {showEmpty ? <EmptyState variant={emptyVariant} /> : <AnswerCard exchange={{ ...exchange, thinking }} />}
            </div>
          )}
        </div>

        <InputBar
          onSubmit={handleAsk}
          thinking={thinking}
          webSearchEnabled={webSearchEnabled}
          onToggleWebSearch={setWebSearchEnabled}
        />
      </main>

      <aside className="w-16 h-full flex flex-col items-center py-8 gap-8 border-l border-outline-variant/10 z-20 shrink-0 hidden lg:flex">
        <div className="w-px h-16 bg-gradient-to-b from-transparent to-outline-variant/30" />
        <div className="flex flex-col gap-4">
          <div className="w-2 h-2 rounded-full bg-primary shadow-[0_0_8px_rgba(255,217,167,0.5)]" />
          <div className="w-1.5 h-1.5 rounded-full bg-outline-variant/40 hover:bg-primary transition-colors cursor-pointer" />
          <div className="w-1.5 h-1.5 rounded-full bg-outline-variant/40 hover:bg-primary transition-colors cursor-pointer" />
        </div>
      </aside>
    </div>
  )
}
